// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadUrl(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:boolean,arg7:boolean,arg8:boolean):Promise<boolean>;

export function GetAllowedHosts():Promise<Array<string>>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;
