// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadUrl(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['SlavartdlUI']['DownloadUrl'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GetAllowedHosts() {
  return window['go']['main']['SlavartdlUI']['GetAllowedHosts']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['SlavartdlUI']['Login'](arg1, arg2);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['SlavartdlUI']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['SlavartdlUI']['OpenFileDialog'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['SlavartdlUI']['SaveFileDialog'](arg1);
}
