// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['SlavartdlUI']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['SlavartdlUI']['OpenFileDialog'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['SlavartdlUI']['SaveFileDialog'](arg1);
}
