// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileDialog(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;
